### ISSUE TITLE
Some vWii titles are missing

### ISSUE THREAD

**Issue by connesc** [GabyPCgeeK/savemii#3]
Mario Kart Wii is not shown in my vWii title list.
By comparing the results with [savegame-manager-gx](https://sourceforge.net/projects/savegame-manager-gx/), I also noticed that the Homebrew Channel is not shown either (not a problem by itself).

The issue is probably related to title IDs in some way:
- Mario Kart Wii: **00010004**524d4350
- The Homebrew Channel: **00010001**4c554c5a

All my other titles start by 00010000 and are correctly shown.

Looking at [here](http://wiibrew.org/wiki/Title_database) and [there](http://wiibrew.org/wiki/Disc_based_games), 00010004 appears to be relevant, although mainly used for Mario Kart Wii. Also, 00010001 might be interesting, but not sure.

**Comment by GabyPCgeeK** [comment]
Added support for 00010001 and 00010004. Currently testing features added so new release will be released some time between tomorrow and Saturday.

**Comment by connesc** [comment]
Nice, thanks ! 👍
I will test this ASAP.

**Comment by connesc** [comment]
The latest release is awesome! :tada: 
I confirm this is fixed now.

Side note: if possible, it would be really convenient to update the version registered in the [Homebrew App Store](https://www.wiiubru.com/appstore/#/app/savemii_mod) as well.
